(defvar-keymap my/window-map
  :doc "window management keybinds"
  "h" #'split-window-horizontally
  "v" #'split-window-vertically
  "d" #'delete-other-windows
  "k" #'delete-window)

(keymap-global-set "C-c w" my/window-map)
(keymap-global-set "C-c p" project-prefix-map)

(keymap-global-set "M-/"   #'completion-at-point)
(keymap-global-set "M-h"   #'windmove-left)
(keymap-global-set "M-l"   #'windmove-right)
(keymap-global-set "M-k"   #'windmove-up)
(keymap-global-set "M-j"   #'windmove-down)
(keymap-global-set "C-c a" #'save-buffer)

;; embark
(keymap-global-set "C-."   #'embark-act)
(keymap-global-set "C-,"   #'embark-export)
(keymap-global-set "C-;"   #'embark-dwim)
(keymap-global-set "C-h B" #'embark-bindings)

(setq prefix-help-command #'embark-prefix-help-command)

(defun my/page-down ()
  (interactive)
  (next-line (/ (window-total-height) 2))
  (recenter))

(defun my/page-up ()
  (interactive)
  (previous-line (/ (window-total-height) 2))
  (recenter))

(defun my/buffer-dwim ()
  (interactive)
  (consult-buffer))

(defun my/find-dwim ()
  (interactive)
  (consult-fd))

(defun my/rg-dwim ()
  (interactive)
  (consult-ripgrep))

(require 'meow)

(setq meow-use-clipboard t)
(setq meow-use-cursor-position-hack nil)

(meow-thing-register 'angle '(regexp "<" ">") '(regexp "<" ">"))
(add-to-list 'meow-char-thing-table '(?a . angle))
(defun meow-end-of-line () (interactive) (meow-end-of-thing ?l))

(require 'hydra)

(defhydra hydra-surround (:color blue)
  "Surround..."
  ("s" surround-insert "surround")
  ("c" surround-change "change")
  ("k" surround-kill "kill inner")
  ("K" surround-kill-outer "kill outer")
  ("q" nil "close"))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-define-key
   '("j" . meow-next)
   '("k" . meow-prev)
   '("D" . my/page-down)
   '("U" . my/page-up)
   '("<escape>" . ignore))
  (meow-leader-define-key
   '("SPC b" . consult-buffer)
   '("SPC f" . consult-fd)
   '("SPC s" . consult-ripgrep)
   '("z" . popper-toggle)
   '("b" . my/buffer-dwim)
   '("f" . my/find-dwim)
   '("s" . my/rg-dwim)
   '("SPC g" . magit-status)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("M-h" . windmove-left)
   '("M-l" . windmove-right)
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(":" . replace-regexp)
   '(";" . meow-reverse)
   '("si" . meow-inner-of-thing)
   '("so" . meow-bounds-of-thing)
   '("se" . meow-end-of-thing)
   '("$"  . meow-end-of-line)
   '("a" . meow-append)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-kill)
   '("D" . my/page-down)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("O" . meow-open-above)
   '("o" . meow-open-below)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . hydra-surround/body)
   '("n" . meow-search)
   '("N" . meow-pop-search)
   '("." . meow-block)
   ;; '(">" . meow-to-block)
   '(">" . mc/mark-next-like-this)
   '("<" . mc/mark-previous-like-this)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . my/page-up)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . consult-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab) ;; useless
   '("/" . consult-line)
   '("?" . consult-outline)
   '("z" . meow-join)
   '("'" . repeat)
   '("<escape>" . ignore)))

(meow-setup)
(meow-global-mode 1)

(provide 'my-keybind)
